[package]
name = "ff_python"
version = "0.5.0"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
name = "fuzzyfold"
crate-type = ["cdylib"]

[dependencies]
ff_structure.workspace = true
ff_energy.workspace = true
ff_kinetics.workspace = true
ff_shared = { path = "../fuzzyfold", package = "fuzzyfold" }
rand.workspace = true
rustc-hash.workspace = true
pyo3 = { version = "0.23", features = ["extension-module"] }
rayon = "1.11.0"

